server.port=${SERVER_PORT:8080}
spring.application.name=biblioteca-bff

# Oracle DataSource
spring.datasource.url=${DB_URL:jdbc:oracle:thin:@gibi3xseta997y7i_tp?TNS_ADMIN=/home/rmji/Projects/duoc/b6/cn2/Wallet_GIBI3XSETA997Y7I}
spring.datasource.username=${DB_USER:ADMIN}
spring.datasource.password=${DB_PASSWORD:aWxpYqvej@bUin3P!tbP}
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver

# Hibernate / JPA
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true

# FaaS REST endpoints
fn.usuarios.url=${FN_USUARIOS_URL:https://exp2-usuarios-d7gdduepc3etf6ga.brazilsouth-01.azurewebsites.net}
fn.reservas.url=${FN_RESERVAS_URL:https://exp2-reservas-bhfxdyeqchhkh7bc.brazilsouth-01.azurewebsites.net}

# FaaS GraphQL endpoints
fn.libros.url=${FN_LIBROS_URL:https://exp2-libros-babgfdhjg8dec6c4.brazilsouth-01.azurewebsites.net}
fn.prestamos.url=${FN_PRESTAMOS_URL:https://exp2-prestamos-hnenhffdc4ecgnea.brazilsouth-01.azurewebsites.net}

spring.cloud.openfeign.client.config.default.connect-timeout=5000
spring.cloud.openfeign.client.config.default.read-timeout=10000
spring.cloud.openfeign.discovery.enabled=false

logging.level.cl.duocuc.biblioteca.bff.clients=DEBUG
