-- ============================================================
-- Sistema de Biblioteca - Script de inicializacion Oracle
-- ============================================================

-- Tabla de usuarios
CREATE TABLE USUARIOS (
    ID        NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE    VARCHAR2(100) NOT NULL,
    APELLIDO  VARCHAR2(100) NOT NULL,
    EMAIL     VARCHAR2(200) NOT NULL,
    TELEFONO  VARCHAR2(20),
    CONSTRAINT UK_USUARIO_EMAIL UNIQUE (EMAIL)
);

-- Tabla de libros
CREATE TABLE LIBROS (
    ID         NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TITULO     VARCHAR2(200) NOT NULL,
    AUTOR      VARCHAR2(200) NOT NULL,
    ISBN       VARCHAR2(50)  NOT NULL,
    DISPONIBLE NUMBER(1)     DEFAULT 1 NOT NULL,
    CONSTRAINT UK_LIBRO_ISBN UNIQUE (ISBN),
    CONSTRAINT CK_LIBRO_DISPONIBLE CHECK (DISPONIBLE IN (0, 1))
);

-- Tabla de prestamos
CREATE TABLE PRESTAMOS (
    ID               NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USUARIO_ID       NUMBER       NOT NULL,
    LIBRO_ID         NUMBER       NOT NULL,
    FECHA_PRESTAMO   DATE         DEFAULT SYSDATE NOT NULL,
    FECHA_DEVOLUCION DATE,
    ESTADO           VARCHAR2(20) DEFAULT 'ACTIVO' NOT NULL,
    CONSTRAINT FK_PRESTAMO_USUARIO FOREIGN KEY (USUARIO_ID) REFERENCES USUARIOS(ID),
    CONSTRAINT FK_PRESTAMO_LIBRO   FOREIGN KEY (LIBRO_ID)   REFERENCES LIBROS(ID),
    CONSTRAINT CK_PRESTAMO_ESTADO  CHECK (ESTADO IN ('ACTIVO', 'DEVUELTO', 'VENCIDO'))
);

-- Tabla de reservas
CREATE TABLE RESERVAS (
    ID             NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USUARIO_ID     NUMBER       NOT NULL,
    LIBRO_ID       NUMBER       NOT NULL,
    FECHA_RESERVA  DATE         DEFAULT SYSDATE NOT NULL,
    ESTADO         VARCHAR2(20) DEFAULT 'PENDIENTE' NOT NULL,
    CONSTRAINT FK_RESERVA_USUARIO FOREIGN KEY (USUARIO_ID) REFERENCES USUARIOS(ID),
    CONSTRAINT FK_RESERVA_LIBRO   FOREIGN KEY (LIBRO_ID)   REFERENCES LIBROS(ID),
    CONSTRAINT CK_RESERVA_ESTADO  CHECK (ESTADO IN ('PENDIENTE', 'COMPLETADA', 'CANCELADA'))
);

-- ============================================================
-- Datos de prueba
-- ============================================================

INSERT INTO USUARIOS (NOMBRE, APELLIDO, EMAIL, TELEFONO)
    VALUES ('Juan', 'Perez', 'juan.perez@correo.cl', '+56912345678');
INSERT INTO USUARIOS (NOMBRE, APELLIDO, EMAIL, TELEFONO)
    VALUES ('Maria', 'Gonzalez', 'maria.gonzalez@correo.cl', '+56987654321');
INSERT INTO USUARIOS (NOMBRE, APELLIDO, EMAIL, TELEFONO)
    VALUES ('Carlos', 'Romero', 'carlos.romero@correo.cl', NULL);

INSERT INTO LIBROS (TITULO, AUTOR, ISBN, DISPONIBLE)
    VALUES ('Cien anos de soledad', 'Gabriel Garcia Marquez', '978-0-06-088328-7', 1);
INSERT INTO LIBROS (TITULO, AUTOR, ISBN, DISPONIBLE)
    VALUES ('Don Quijote de la Mancha', 'Miguel de Cervantes', '978-84-376-0494-7', 1);
INSERT INTO LIBROS (TITULO, AUTOR, ISBN, DISPONIBLE)
    VALUES ('El alquimista', 'Paulo Coelho', '978-0-06-112241-5', 0);
INSERT INTO LIBROS (TITULO, AUTOR, ISBN, DISPONIBLE)
    VALUES ('1984', 'George Orwell', '978-0-452-28423-4', 1);

INSERT INTO PRESTAMOS (USUARIO_ID, LIBRO_ID, FECHA_PRESTAMO, ESTADO)
    VALUES (1, 3, SYSDATE, 'ACTIVO');
INSERT INTO PRESTAMOS (USUARIO_ID, LIBRO_ID, FECHA_PRESTAMO, FECHA_DEVOLUCION, ESTADO)
    VALUES (2, 1, SYSDATE - 10, SYSDATE - 2, 'DEVUELTO');

INSERT INTO RESERVAS (USUARIO_ID, LIBRO_ID, FECHA_RESERVA, ESTADO)
    VALUES (3, 2, SYSDATE, 'PENDIENTE');
INSERT INTO RESERVAS (USUARIO_ID, LIBRO_ID, FECHA_RESERVA, ESTADO)
    VALUES (1, 4, SYSDATE - 1, 'COMPLETADA');

COMMIT;
